"""Translation string definitions for all supported languages."""

from __future__ import annotations

STRINGS: dict[str, dict[str, str]] = {
    "en": {
        # Authentication - Login
        "auth.login.success": "Login successful",
        "auth.login.failed": "Invalid credentials",
        "auth.login.locked": "Account is locked",
        "auth.login.disabled": "Account is disabled",
        "auth.login.mfa_required": "Multi-factor authentication required",
        "auth.login.mfa_invalid": "Invalid MFA code",
        "auth.login.session_limit": "Maximum session limit reached",
        "auth.login.suspicious_activity": "Suspicious activity detected on your account",
        "auth.login.password_expired": "Your password has expired. Please reset it.",
        # Authentication - Logout
        "auth.logout.success": "Logged out successfully",
        "auth.logout.all_sessions": "All sessions terminated",
        "auth.logout.failed": "Logout failed",
        # Authentication - Registration
        "auth.registration.success": "Registration successful",
        "auth.registration.username_taken": "Username is already taken",
        "auth.registration.password_weak": "Password does not meet requirements",
        "auth.registration.password_mismatch": "Passwords do not match",
        "auth.registration.email_taken": "Email address is already registered",
        "auth.registration.email_invalid": "Invalid email address format",
        "auth.registration.disabled": "Registration is currently disabled",
        "auth.registration.rate_limited": "Too many registration attempts. Please try again later.",
        # Authentication - Password
        "auth.password.changed": "Password changed successfully",
        "auth.password.reset_sent": "Password reset email sent",
        "auth.password.reset_invalid": "Invalid or expired password reset token",
        "auth.password.reset_success": "Password has been reset successfully",
        "auth.password.policy_violation": "Password does not meet security policy requirements",
        "auth.password.reused": "Cannot reuse a recent password",
        # Validation
        "validation.required": "This field is required",
        "validation.username.length": "Username must be between {min} and {max} characters",
        "validation.username.invalid": "Username contains invalid characters",
        "validation.password.length": "Password must be at least {min} characters",
        "validation.password.uppercase": "Password must contain at least one uppercase letter",
        "validation.password.lowercase": "Password must contain at least one lowercase letter",
        "validation.password.number": "Password must contain at least one number",
        "validation.password.special": "Password must contain at least one special character",
        "validation.email.invalid": "Invalid email address",
        "validation.email.required": "Email address is required",
        "validation.display_name.length": "Display name must be between 1 and 100 characters",
        "validation.field_too_long": "Field must be at most {max} characters",
        "validation.field_too_short": "Field must be at least {min} characters",
        "validation.invalid_format": "Invalid format",
        "validation.numeric_required": "Value must be a number",
        # Sessions
        "session.expired": "Session has expired",
        "session.invalid": "Invalid session",
        "session.created": "Session created",
        "session.terminated": "Session terminated",
        "session.renewed": "Session renewed",
        "session.not_found": "Session not found",
        "session.max_terminated": "Maximum sessions reached. Oldest session terminated.",
        "session.device_changed": "Session device mismatch detected",
        # Users
        "user.not_found": "User not found",
        "user.created": "User created successfully",
        "user.updated": "User updated successfully",
        "user.deleted": "User deleted successfully",
        "user.already_exists": "User already exists",
        "user.status_changed": "User status updated",
        "user.profile_updated": "Profile updated successfully",
        "user.preferences_updated": "Preferences saved successfully",
        "user.avatar_updated": "Avatar updated successfully",
        "user.account_locked": "Account has been locked due to security concerns",
        "user.account_unlocked": "Account has been unlocked",
        # Roles & Permissions
        "role.created": "Role created successfully",
        "role.updated": "Role updated successfully",
        "role.deleted": "Role deleted successfully",
        "role.not_found": "Role not found",
        "role.assigned": "Role assigned to user",
        "role.removed": "Role removed from user",
        "permission.denied": "You do not have permission to perform this action",
        "permission.granted": "Permission granted",
        # Policies
        "policy.created": "Policy created successfully",
        "policy.updated": "Policy updated successfully",
        "policy.deleted": "Policy deleted successfully",
        "policy.not_found": "Policy not found",
        "policy.enabled": "Policy enabled",
        "policy.disabled": "Policy disabled",
        "policy.already_exists": "A policy with this name already exists",
        "policy.evaluation_complete": "Policy evaluation complete",
        "policy.import_success": "Policies imported successfully",
        "policy.export_success": "Policies exported successfully",
        "policy.invalid_transition": "Invalid policy status transition",
        # Audit
        "audit.event_logged": "Audit event logged",
        "audit.export_started": "Audit log export started",
        "audit.export_complete": "Audit log export complete",
        "audit.search_complete": "Audit search completed",
        "audit.no_results": "No audit events match the search criteria",
        # General - Success
        "success.operation_complete": "Operation completed successfully",
        "success.saved": "Changes saved successfully",
        "success.deleted": "Item deleted successfully",
        "success.updated": "Item updated successfully",
        # General - Errors
        "error.internal": "An internal error occurred",
        "error.not_found": "Resource not found",
        "error.unauthorized": "Authentication required",
        "error.forbidden": "Access denied",
        "error.validation": "Validation failed",
        "error.conflict": "Resource already exists",
        "error.rate_limited": "Too many requests. Please try again later.",
        "error.service_unavailable": "Service temporarily unavailable",
        "error.timeout": "Request timed out",
        "error.bad_request": "Bad request",
        # Security
        "security.violation": "Security policy violation detected",
        "security.network_blocked": "Network target not allowed - this application only supports localhost",
        "security.rate_limit": "Rate limit exceeded for this operation",
        "security.too_many_attempts": "Too many failed attempts. Account locked.",
        "security.ip_blocked": "IP address has been blocked",
        "security.brute_force_detected": "Potential brute force attack detected",
        # Accessibility
        "accessibility.screen_reader_optimized": "Screen reader mode enabled",
        "accessibility.high_contrast": "High contrast mode enabled",
        "accessibility.reduce_motion": "Reduced motion mode enabled",
        "accessibility.keyboard_nav": "Keyboard navigation mode enabled",
        "accessibility.preferences_saved": "Accessibility preferences saved",
        # Learning
        "learning.module_started": "Learning module started",
        "learning.module_completed": "Learning module completed",
        "learning.progress_saved": "Learning progress saved",
        "learning.certificate_earned": "Certificate earned",
        # General info
        "info.welcome": "Welcome to AuthShieldLab",
        "info.version": "Version {version}",
        "info.environment": "Running in {environment} environment",
    },
    "te": {
        # Authentication - Login
        "auth.login.success": "లాగిన్ విజయవంతమైంది",
        "auth.login.failed": "చెల్లని ఆధారాలు",
        "auth.login.locked": "ఖాతా లాక్ చేయబడింది",
        "auth.login.disabled": "ఖాతా నిలిపివేయబడింది",
        "auth.login.mfa_required": "బహుళ-కారకాంశాల ధృవీకరణ అవసరం",
        "auth.login.mfa_invalid": "చెల్లని MFA కోడ్",
        "auth.login.session_limit": "గరిష్ట సెషన్ పరిమితి చేరుకుంది",
        "auth.login.suspicious_activity": "మీ ఖాతాలో అనుమానాస్పద కార్యాచరణ గుర్తించబడింది",
        "auth.login.password_expired": "మీ పాస్‌వర్డ్ గడువు ముగిసింది. దయచేసి రీసెట్ చేయండి.",
        # Authentication - Logout
        "auth.logout.success": "లాగ్అవుట్ విజయవంతమైంది",
        "auth.logout.all_sessions": "అన్ని సెషన్లు ముగించబడ్డాయి",
        "auth.logout.failed": "లాగ్అవుట్ విఫలమైంది",
        # Authentication - Registration
        "auth.registration.success": "నమోదు విజయవంతమైంది",
        "auth.registration.username_taken": "వినియోగదారు నామం ఇప్పటికే తీసుకోబడింది",
        "auth.registration.password_weak": "పాస్‌వర్డ్ అవసరాలను తీర్చలేదు",
        "auth.registration.password_mismatch": "పాస్‌వర్డ్‌లు సరిపోలడం లేదు",
        "auth.registration.email_taken": "ఇమెయిల్ చిరునామా ఇప్పటికే నమోదైంది",
        "auth.registration.email_invalid": "చెల్లని ఇమెయిల్ ఫార్మాట్",
        "auth.registration.disabled": "నమోదు ప్రస్తుతం నిలిపివేయబడింది",
        "auth.registration.rate_limited": "చాలా నమోదు ప్రయత్నాలు. దయచేసి తర్వాత మళ్ళీ ప్రయత్నించండి.",
        # Authentication - Password
        "auth.password.changed": "పాస్‌వర్డ్ విజయవంతంగా మార్చబడింది",
        "auth.password.reset_sent": "పాస్‌వర్డ్ రీసెట్ ఇమెయిల్ పంపబడింది",
        "auth.password.reset_invalid": "చెల్లని లేదా గడువు ముగిసిన పాస్‌వర్డ్ రీసెట్ టోకెన్",
        "auth.password.reset_success": "పాస్‌వర్డ్ విజయవంతంగా రీసెట్ చేయబడింది",
        "auth.password.policy_violation": "పాస్‌వర్డ్ భద్రతా విధాన అవసరాలను తీర్చలేదు",
        "auth.password.reused": "ఇటీవలి పాస్‌వర్డ్ మళ్ళీ ఉపయోగించలేరు",
        # Validation
        "validation.required": "ఈ ఫీల్డ్ అవసరం",
        "validation.username.length": "వినియోగదారు నామం {min} మరియు {max} అక్షరాల మధ్య ఉండాలి",
        "validation.username.invalid": "వినియోగదారు నామంలో చెల్లని అక్షరాలు ఉన్నాయి",
        "validation.password.length": "పాస్‌వర్డ్ కనీసం {min} అక్షరాలు ఉండాలి",
        "validation.password.uppercase": "పాస్‌వర్డ్ కనీసం ఒక పెద్ద అక్షరం కలిగి ఉండాలి",
        "validation.password.lowercase": "పాస్‌వర్డ్ కనీసం ఒక చిన్న అక్షరం కలిగి ఉండాలి",
        "validation.password.number": "పాస్‌వర్డ్ కనీసం ఒక సంఖ్య కలిగి ఉండాలి",
        "validation.password.special": "పాస్‌వర్డ్ కనీసం ఒక ప్రత్యేక అక్షరం కలిగి ఉండాలి",
        "validation.email.invalid": "చెల్లని ఇమెయిల్ చిరునామా",
        "validation.email.required": "ఇమెయిల్ చిరునామా అవసరం",
        "validation.display_name.length": "ప్రదర్శన నామం 1 మరియు 100 అక్షరాల మధ్య ఉండాలి",
        "validation.field_too_long": "ఫీల్డ్ గరిష్టంగా {max} అక్షరాలు ఉండాలి",
        "validation.field_too_short": "ఫీల్డ్ కనీసం {min} అక్షరాలు ఉండాలి",
        "validation.invalid_format": "చెల్లని ఫార్మాట్",
        "validation.numeric_required": "విలువ సంఖ్యగా ఉండాలి",
        # Sessions
        "session.expired": "సెషన్ గడువు ముగిసింది",
        "session.invalid": "చెల్లని సెషన్",
        "session.created": "సెషన్ సృష్టించబడింది",
        "session.terminated": "సెషన్ ముగించబడింది",
        "session.renewed": "సెషన్ పునరుద్ధరించబడింది",
        "session.not_found": "సెషన్ కనుగొనబడలేదు",
        "session.max_terminated": "గరిష్ట సెషన్లు చేరుకున్నాయి. పాత సెషన్ ముగించబడింది.",
        "session.device_changed": "సెషన్ పరికరం మార్పు గుర్తించబడింది",
        # Users
        "user.not_found": "వినియోగదారు కనుగొనబడలేదు",
        "user.created": "వినియోగదారు విజయవంతంగా సృష్టించబడారు",
        "user.updated": "వినియోగదారు విజయవంతంగా నవీకరించబడారు",
        "user.deleted": "వినియోగదారు విజయవంతంగా తొలగించబడారు",
        "user.already_exists": "వినియోగదారు ఇప్పటికే ఉన్నారు",
        "user.status_changed": "వినియోగదారు స్థితి నవీకరించబడింది",
        "user.profile_updated": "ప్రొఫైల్ విజయవంతంగా నవీకరించబడింది",
        "user.preferences_updated": "ప్రాధాన్యతలు విజయవంతంగా సేవ్ చేయబడ్డాయి",
        "user.avatar_updated": "అవతార్ విజయవంతంగా నవీకరించబడింది",
        "user.account_locked": "భద్రతా కారణాల వల్ల ఖాతా లాక్ చేయబడింది",
        "user.account_unlocked": "ఖాతా అన్‌లాక్ చేయబడింది",
        # Roles & Permissions
        "role.created": "పాత్ర విజయవంతంగా సృష్టించబడింది",
        "role.updated": "పాత్ర విజయవంతంగా నవీకరించబడింది",
        "role.deleted": "పాత్ర విజయవంతంగా తొలగించబడింది",
        "role.not_found": "పాత్ర కనుగొనబడలేదు",
        "role.assigned": "వినియోగదారుకు పాత్ర కేటాయించబడింది",
        "role.removed": "వినియోగదారు నుండి పాత్ర తీసివేయబడింది",
        "permission.denied": "ఈ చర్యను నిర్వహించడానికి మీకు అనుమతి లేదు",
        "permission.granted": "అనుమతి ఇవ్వబడింది",
        # Policies
        "policy.created": "విధానం విజయవంతంగా సృష్టించబడింది",
        "policy.updated": "విధానం విజయవంతంగా నవీకరించబడింది",
        "policy.deleted": "విధానం విజయవంతంగా తొలగించబడింది",
        "policy.not_found": "విధానం కనుగొనబడలేదు",
        "policy.enabled": "విధానం ప్రారంభించబడింది",
        "policy.disabled": "విధానం నిలిపివేయబడింది",
        "policy.already_exists": "ఈ పేరుతో విధానం ఇప్పటికే ఉంది",
        "policy.evaluation_complete": "విధాన మూల్యాంకనం పూర్తయింది",
        "policy.import_success": "విధానాలు విజయవంతంగా దిగుమతి చేయబడ్డాయి",
        "policy.export_success": "విధానాలు విజయవంతంగా ఎగుమతి చేయబడ్డాయి",
        "policy.invalid_transition": "చెల్లని విధాన స్థితి పరివర్తన",
        # Audit
        "audit.event_logged": "ఆడిట్ ఈవెంట్ లాగ్ చేయబడింది",
        "audit.export_started": "ఆడిట్ లాగ్ ఎగుమతి ప్రారంభమైంది",
        "audit.export_complete": "ఆడిట్ లాగ్ ఎగుమతి పూర్తయింది",
        "audit.search_complete": "ఆడిట్ శోధన పూర్తయింది",
        "audit.no_results": "శోధన ప్రమాణాలకు ఆడిట్ ఈవెంట్లు సరిపోలడం లేదు",
        # General - Success
        "success.operation_complete": "కార్యాచరణ విజయవంతంగా పూర్తయింది",
        "success.saved": "మార్పులు విజయవంతంగా సేవ్ చేయబడ్డాయి",
        "success.deleted": "అంశం విజయవంతంగా తొలగించబడింది",
        "success.updated": "అంశం విజయవంతంగా నవీకరించబడింది",
        # General - Errors
        "error.internal": "అంతర్గత దోషం సంభవించింది",
        "error.not_found": "వనరు కనుగొనబడలేదు",
        "error.unauthorized": "ధృవీకరణ అవసరం",
        "error.forbidden": "యాక్సెస్ నిరాకరించబడింది",
        "error.validation": "ధృవీకరణ విఫలమైంది",
        "error.conflict": "వనరు ఇప్పటికే ఉంది",
        "error.rate_limited": "చాలా అభ్యర్థనలు. దయచేసి తర్వాత మళ్ళీ ప్రయత్నించండి.",
        "error.service_unavailable": "సేవ తాత్కాలికంగా అందుబాటులో లేదు",
        "error.timeout": "అభ్యర్థన సమయం ముగిసింది",
        "error.bad_request": "చెల్లని అభ్యర్థన",
        # Security
        "security.violation": "భద్రతా విధాన ఉల్లంఘన గుర్తించబడింది",
        "security.network_blocked": "నెట్‌వర్క్ లక్ష్యం అనుమతించబడలేదు - ఈ అప్లికేషన్ లోకల్‌హోస్ట్‌ను మాత్రమే మద్దతు ఇస్తుంది",
        "security.rate_limit": "ఈ కార్యాచరణకు రేటు పరిమితి మించింది",
        "security.too_many_attempts": "చాలా విఫల ప్రయత్నాలు. ఖాతా లాక్ చేయబడింది.",
        "security.ip_blocked": "IP చిరునామా బ్లాక్ చేయబడింది",
        "security.brute_force_detected": "సంభావ్య బ్రూట్ ఫోర్స్ దాడి గుర్తించబడింది",
        # Accessibility
        "accessibility.screen_reader_optimized": "స్క్రీన్ రీడర్ మోడ్ ప్రారంభించబడింది",
        "accessibility.high_contrast": "అధిక కాంట్రాస్ట్ మోడ్ ప్రారంభించబడింది",
        "accessibility.reduce_motion": "తగ్గించిన చలనం మోడ్ ప్రారంభించబడింది",
        "accessibility.keyboard_nav": "కీబోర్డ్ నావిగేషన్ మోడ్ ప్రారంభించబడింది",
        "accessibility.preferences_saved": "ప్రాప్యత ప్రాధాన్యతలు సేవ్ చేయబడ్డాయి",
        # Learning
        "learning.module_started": "అభ్యాస మాడ్యూల్ ప్రారంభమైంది",
        "learning.module_completed": "అభ్యాస మాడ్యూల్ పూర్తయింది",
        "learning.progress_saved": "అభ్యాస పురోగతి సేవ్ చేయబడింది",
        "learning.certificate_earned": "సర్టిఫికేట్ సంపాదించబడింది",
        # General info
        "info.welcome": "AuthShieldLab కు స్వాగతం",
        "info.version": "వెర్షన్ {version}",
        "info.environment": "{environment} వాతావరణంలో నడుస్తోంది",
    },
    "hi": {
        # Authentication - Login
        "auth.login.success": "लॉगिन सफल",
        "auth.login.failed": "अमान्य प्रमाण-पत्र",
        "auth.login.locked": "खाता लॉक किया गया है",
        "auth.login.disabled": "खाता अक्षम किया गया है",
        "auth.login.mfa_required": "बहु-कारक प्रमाणीकरण आवश्यक",
        "auth.login.mfa_invalid": "अमान्य MFA कोड",
        "auth.login.session_limit": "अधिकतम सत्र सीमा पहुँच गई",
        "auth.login.suspicious_activity": "आपके खाते में संदिग्ध गतिविधि का पता चला",
        "auth.login.password_expired": "आपका पासवर्ड की अवधि समाप्त हो गई है। कृपया इसे रीसेट करें।",
        # Authentication - Logout
        "auth.logout.success": "लॉगआउट सफल",
        "auth.logout.all_sessions": "सभी सत्र समाप्त किए गए",
        "auth.logout.failed": "लॉगआउट विफल",
        # Authentication - Registration
        "auth.registration.success": "पंजीकरण सफल",
        "auth.registration.username_taken": "उपयोगकर्ता नाम पहले से लिया गया है",
        "auth.registration.password_weak": "पासवर्ड आवश्यकताओं को पूरा नहीं करता",
        "auth.registration.password_mismatch": "पासवर्ड मेल नहीं खाते",
        "auth.registration.email_taken": "ईमेल पता पहले से पंजीकृत है",
        "auth.registration.email_invalid": "अमान्य ईमेल पता प्रारूप",
        "auth.registration.disabled": "पंजीकरण वर्तमान में अक्षम है",
        "auth.registration.rate_limited": "बहुत अधिक पंजीकरण प्रयास। कृपया बाद में पुनः प्रयास करें।",
        # Authentication - Password
        "auth.password.changed": "पासवर्ड सफलतापूर्वक बदला गया",
        "auth.password.reset_sent": "पासवर्ड रीसेट ईमेल भेजा गया",
        "auth.password.reset_invalid": "अमान्य या समय-सीमा समाप्त पासवर्ड रीसेट टोकन",
        "auth.password.reset_success": "पासवर्ड सफलतापूर्वक रीसेट किया गया",
        "auth.password.policy_violation": "पासवर्ड सुरक्षा नीति आवश्यकताओं को पूरा नहीं करता",
        "auth.password.reused": "हाल के पासवर्ड का पुनः उपयोग नहीं किया जा सकता",
        # Validation
        "validation.required": "यह फ़ील्ड आवश्यक है",
        "validation.username.length": "उपयोगकर्ता नाम {min} और {max} अक्षरों के बीच होना चाहिए",
        "validation.username.invalid": "उपयोगकर्ता नाम में अमान्य अक्षर हैं",
        "validation.password.length": "पासवर्ड कम से कम {min} अक्षरों का होना चाहिए",
        "validation.password.uppercase": "पासवर्ड में कम से कम एक बड़ा अक्षर होना चाहिए",
        "validation.password.lowercase": "पासवर्ड में कम से कम एक छोटा अक्षर होना चाहिए",
        "validation.password.number": "पासवर्ड में कम से कम एक संख्या होनी चाहिए",
        "validation.password.special": "पासवर्ड में कम से कम एक विशेष अक्षर होना चाहिए",
        "validation.email.invalid": "अमान्य ईमेल पता",
        "validation.email.required": "ईमेल पता आवश्यक है",
        "validation.display_name.length": "प्रदर्शन नाम 1 और 100 अक्षरों के बीच होना चाहिए",
        "validation.field_too_long": "फ़ील्ड अधिकतम {max} अक्षरों की होनी चाहिए",
        "validation.field_too_short": "फ़ील्ड कम से कम {min} अक्षरों की होनी चाहिए",
        "validation.invalid_format": "अमान्य प्रारूप",
        "validation.numeric_required": "मान संख्या होनी चाहिए",
        # Sessions
        "session.expired": "सत्र की अवधि समाप्त हो गई",
        "session.invalid": "अमान्य सत्र",
        "session.created": "सत्र बनाया गया",
        "session.terminated": "सत्र समाप्त किया गया",
        "session.renewed": "सत्र नवीनीकृत किया गया",
        "session.not_found": "सत्र नहीं मिला",
        "session.max_terminated": "अधिकतम सत्र पहुँच गए। पुराना सत्र समाप्त किया गया।",
        "session.device_changed": "सत्र डिवाइस परिवर्तन का पता चला",
        # Users
        "user.not_found": "उपयोगकर्ता नहीं मिला",
        "user.created": "उपयोगकर्ता सफलतापूर्वक बनाया गया",
        "user.updated": "उपयोगकर्ता सफलतापूर्वक अपडेट किया गया",
        "user.deleted": "उपयोगकर्ता सफलतापूर्वक हटाया गया",
        "user.already_exists": "उपयोगकर्ता पहले से मौजूद है",
        "user.status_changed": "उपयोगकर्ता स्थिति अपडेट की गई",
        "user.profile_updated": "प्रोफ़ाइल सफलतापूर्वक अपडेट की गई",
        "user.preferences_updated": "प्राथमिकताएँ सफलतापूर्वक सहेजी गईं",
        "user.avatar_updated": "अवतार सफलतापूर्वक अपडेट किया गया",
        "user.account_locked": "सुरक्षा चिंताओं के कारण खाता लॉक किया गया",
        "user.account_unlocked": "खाता अनलॉक किया गया",
        # Roles & Permissions
        "role.created": "भूमिका सफलतापूर्वक बनाई गई",
        "role.updated": "भूमिका सफलतापूर्वक अपडेट की गई",
        "role.deleted": "भूमिका सफलतापूर्वक हटाई गई",
        "role.not_found": "भूमिका नहीं मिली",
        "role.assigned": "उपयोगकर्ता को भूमिका सौंपी गई",
        "role.removed": "उपयोगकर्ता से भूमिका हटाई गई",
        "permission.denied": "इस कार्रवाई को करने की आपको अनुमति नहीं है",
        "permission.granted": "अनुमति दी गई",
        # Policies
        "policy.created": "नीति सफलतापूर्वक बनाई गई",
        "policy.updated": "नीति सफलतापूर्वक अपडेट की गई",
        "policy.deleted": "नीति सफलतापूर्वक हटाई गई",
        "policy.not_found": "नीति नहीं मिली",
        "policy.enabled": "नीति सक्षम की गई",
        "policy.disabled": "नीति अक्षम की गई",
        "policy.already_exists": "इस नाम से एक नीति पहले से मौजूद है",
        "policy.evaluation_complete": "नीति मूल्यांकन पूर्ण",
        "policy.import_success": "नीतियाँ सफलतापूर्वक आयात की गईं",
        "policy.export_success": "नीतियाँ सफलतापूर्वक निर्यात की गईं",
        "policy.invalid_transition": "अमान्य नीति स्थिति संक्रमण",
        # Audit
        "audit.event_logged": "ऑडिट ईवेंट लॉग किया गया",
        "audit.export_started": "ऑडिट लॉग निर्यात शुरू हुआ",
        "audit.export_complete": "ऑडिट लॉग निर्यात पूर्ण",
        "audit.search_complete": "ऑडिट खोज पूर्ण",
        "audit.no_results": "खोज मानदंडों से कोई ऑडिट ईवेंट मेल नहीं खाता",
        # General - Success
        "success.operation_complete": "कार्रवाई सफलतापूर्वक पूर्ण",
        "success.saved": "परिवर्तन सफलतापूर्वक सहेजे गए",
        "success.deleted": "आइटम सफलतापूर्वक हटाया गया",
        "success.updated": "आइटम सफलतापूर्वक अपडेट किया गया",
        # General - Errors
        "error.internal": "आंतरिक त्रुटि हुई",
        "error.not_found": "संसाधन नहीं मिला",
        "error.unauthorized": "प्रमाणीकरण आवश्यक",
        "error.forbidden": "पहुँच अस्वीकृत",
        "error.validation": "सत्यापन विफल",
        "error.conflict": "संसाधन पहले से मौजूद है",
        "error.rate_limited": "बहुत अधिक अनुरोध। कृपया बाद में पुनः प्रयास करें।",
        "error.service_unavailable": "सेवा अस्थायी रूप से उपलब्ध नहीं है",
        "error.timeout": "अनुरोध का समय समाप्त",
        "error.bad_request": "खराब अनुरोध",
        # Security
        "security.violation": "सुरक्षा नीति उल्लंघन का पता चला",
        "security.network_blocked": "नेटवर्क लक्ष्य अनुमति नहीं - यह एप्लिकेशन केवल localhost का समर्थन करता है",
        "security.rate_limit": "इस कार्रवाई के लिए दर सीमा पार",
        "security.too_many_attempts": "बहुत अधिक विफल प्रयास। खाता लॉक किया गया।",
        "security.ip_blocked": "IP पता ब्लॉक किया गया",
        "security.brute_force_detected": "संभावित ब्रूट फोर्स हमले का पता चला",
        # Accessibility
        "accessibility.screen_reader_optimized": "स्क्रीन रीडर मोड सक्षम",
        "accessibility.high_contrast": "उच्च कंट्रास्ट मोड सक्षम",
        "accessibility.reduce_motion": "कम गति मोड सक्षम",
        "accessibility.keyboard_nav": "कीबोर्ड नेविगेशन मोड सक्षम",
        "accessibility.preferences_saved": "पहुँच प्राथमिकताएँ सहेजी गईं",
        # Learning
        "learning.module_started": "शिक्षण मॉड्यूल शुरू",
        "learning.module_completed": "शिक्षण मॉड्यूल पूर्ण",
        "learning.progress_saved": "शिक्षण प्रगति सहेजी गई",
        "learning.certificate_earned": "प्रमाणपत्र अर्जित",
        # General info
        "info.welcome": "AuthShieldLab में आपका स्वागत है",
        "info.version": "संस्करण {version}",
        "info.environment": "{environment} वातावरण में चल रहा है",
    },
}

SUPPORTED_LANGUAGES: list[str] = sorted(STRINGS.keys())
